package net.kodein.powerludo.business


const val SupabaseUrl = "https://axvxgfwwlwjvjhtloygz.supabase.co"
const val SupabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dnhnZnd3bHdqdmpodGxveWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTAwODM3NDYsImV4cCI6MjAyNTY1OTc0Nn0.3n-LKLDnhdjCDUbSAC1J3hs4mAgbiJca702QzkG1zq8"
